# Generated by Django 2.1.8 on 2019-07-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('center_name', models.CharField(max_length=128)),
                ('center_location', models.CharField(max_length=128)),
                ('center_type', models.CharField(max_length=128)),
                ('product_type', models.CharField(max_length=128)),
                ('project_explain', models.CharField(max_length=128)),
                ('date', models.DateField()),
            ],
        ),
    ]
